fragment VariantFragment on ProductVariant {
  id
  title
  presentmentPrices(first: 10) {
    edges {
      node {
        price {
          currencyCode
          amount
        }
      }
    }
  }
  selectedOptions {
    name
    value
  }
  product {
    title
    handle
  }
  image {
    transformedSrc(
      maxHeight: 250
      maxWidth: 250
    )
    altText
  }
}
