#import "@/graphql/shopify/fragments/CollectionFragment.gql"
#import "@/graphql/shopify/fragments/ProductCardFragment.gql"

query collectionByHandleQuery(
  $handle: String!
  $cursor: String
  $sortKey: ProductCollectionSortKeys,
  $reverse: Boolean
) {
  collectionByHandle(handle: $handle) {
    ...CollectionFragment
    products(
      first: 24
      after: $cursor
      sortKey: $sortKey
      reverse: $reverse
    ) {
      pageInfo {
        hasNextPage
      }
      edges {
        cursor
        node {
          ...ProductCardFragment
        }
      }
    }
  }
}
