#import "@/graphql/shopify/fragments/BlogFragment.gql"
#import "@/graphql/shopify/fragments/ArticleCardFragment.gql"

query blogByHandleQuery($handle: String!, $cursor: String) {
  blogByHandle(handle: $handle) {
    ...BlogFragment
    articles(first: 24, after: $cursor, reverse: true) {
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      edges {
        cursor
        node {
          ...ArticleCardFragment
        }
      }
    }
  }
}
