query productContentByHandleQuery($handle: String!) {
  allProduct(
    where: { handle: { current: { eq: $handle } } }
    limit: 1
  ) {
    heading
    description: descriptionRaw
    images {
      alt
      asset {
        url
      }
    }
  }
}
